<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NigeriaLocationsSeeder extends Seeder
{
    public function run()
    {
        // Insert States
        $states = [
            ['name' => 'Abia', 'code' => 'AB'],
            ['name' => 'Adamawa', 'code' => 'AD'],
            ['name' => 'Akwa Ibom', 'code' => 'AK'],
            ['name' => 'Anambra', 'code' => 'AN'],
            ['name' => 'Bauchi', 'code' => 'BA'],
            ['name' => 'Bayelsa', 'code' => 'BY'],
            ['name' => 'Benue', 'code' => 'BE'],
            ['name' => 'Borno', 'code' => 'BO'],
            ['name' => 'Cross River', 'code' => 'CR'],
            ['name' => 'Delta', 'code' => 'DE'],
            ['name' => 'Ebonyi', 'code' => 'EB'],
            ['name' => 'Edo', 'code' => 'ED'],
            ['name' => 'Ekiti', 'code' => 'EK'],
            ['name' => 'Enugu', 'code' => 'EN'],
            ['name' => 'Gombe', 'code' => 'GO'],
            ['name' => 'Imo', 'code' => 'IM'],
            ['name' => 'Jigawa', 'code' => 'JI'],
            ['name' => 'Kaduna', 'code' => 'KD'],
            ['name' => 'Kano', 'code' => 'KN'],
            ['name' => 'Katsina', 'code' => 'KT'],
            ['name' => 'Kebbi', 'code' => 'KE'],
            ['name' => 'Kogi', 'code' => 'KO'],
            ['name' => 'Kwara', 'code' => 'KW'],
            ['name' => 'Lagos', 'code' => 'LA'],
            ['name' => 'Nasarawa', 'code' => 'NA'],
            ['name' => 'Niger', 'code' => 'NI'],
            ['name' => 'Ogun', 'code' => 'OG'],
            ['name' => 'Ondo', 'code' => 'ON'],
            ['name' => 'Osun', 'code' => 'OS'],
            ['name' => 'Oyo', 'code' => 'OY'],
            ['name' => 'Plateau', 'code' => 'PL'],
            ['name' => 'Rivers', 'code' => 'RI'],
            ['name' => 'Sokoto', 'code' => 'SO'],
            ['name' => 'Taraba', 'code' => 'TA'],
            ['name' => 'Yobe', 'code' => 'YO'],
            ['name' => 'Zamfara', 'code' => 'ZA'],
            ['name' => 'FCT', 'code' => 'FC'],
        ];

        foreach ($states as $state) {
            DB::table('states')->insert($state);
        }

        // LGAs data
        $lgasData = [
            'Abia' => [
                'Bende',
                'Ikwuano',
                'Aba North',
                'Aba South',
                'Arochukwu',
                'Isiala Ngwa North',
                'Isiala Ngwa South',
                'Isuikwuato',
                'Obi Ngwa',
                'Ohafia',
                'Osisioma Ngwa',
                'Ugwunagbo',
                'Ukwa East',
                'Ukwa West',
                'Umuahia North',
                'Umuahia South',
                'Umu Nneochi'
            ],
            'Adamawa' => [
                'Girei',
                'Gombi',
                'Jada',
                'Demsa',
                'Fufore',
                'Ganye',
                'Lamurde',
                'Madagali',
                'Maiha',
                'Mayo-Belwa',
                'Guyuk',
                'Hong',
                'Michika',
                'Numan',
                'Shelleng',
                'Song',
                'Mubi North',
                'Mubi South',
                'Toungo',
                'Yola North',
                'Yola South'
            ],
            'Akwa Ibom' => [
                'Ikono',
                'Eket',
                'Esit-Eket',
                'Abak',
                'Eastern Obolo',
                'Ibesikpo-Asutan',
                'Ibeno',
                'Ibiono-Ibom',
                'Ika',
                'Essien Udim',
                'Etim-Ekpo',
                'Etinan',
                'Nsit-Atai',
                'Nsit-Ibom',
                'Nsit-Ubium',
                'Obot-Akara',
                'Ini',
                'Itu',
                'Mbo',
                'Mkpat-Enin',
                'Ikot Abasi',
                'Ikot Ekpene',
                'Okobo',
                'Onna',
                'Oron',
                'Oruk Anam',
                'Urue-Offong/Oruko',
                'Uyo',
                'Ukanafun',
                'Udung-Uko',
                'Uruan'
            ],
            'Anambra' => [
                'Aguata',
                'Anambra East',
                'Anambra West',
                'Anaocha',
                'Ayamelum',
                'Awka North',
                'Awka South',
                'Ihiala',
                'Njikoka',
                'Nnewi North',
                'Nnewi South',
                'Dunukofia',
                'Ekwusigo',
                'Idemili North',
                'Idemili South',
                'Ogbaru',
                'Onitsha North',
                'Onitsha South',
                'Orumba North',
                'Orumba South',
                'Oyi'
            ],
            'Bauchi' => [
                'Bogoro',
                'Ningi',
                'Warji',
                'Dass',
                'Toro',
                'Ganjuwa',
                'Kirfi',
                'Alkaleri',
                'Bauchi',
                'Tafawa Balewa',
                'Darazo',
                'Misau',
                'Katagum',
                'Itas/Gadau',
                'Giade',
                'Shira',
                'Jama’are',
                'Zaki',
                'Gamawa',
                'Damban'
            ],
            'Bayelsa' => [
                'Kolokuma/Opokuma',
                'Nembe',
                'Ogbia',
                'Sagbama',
                'Brass',
                'Ekeremor',
                'Southern Ijaw',
                'Yenagoa'
            ],
            'Benue' => [
                'Guma',
                'Gwer East',
                'Gwer West',
                'Katsina-Ala',
                'Konshisha',
                'Ado',
                'Buruku',
                'Gboko',
                'Kwande',
                'Logo',
                'Makurdi',
                'Obi',
                'Ogbadibo',
                'Ohimini',
                'Oju',
                'Agatu',
                'Apa',
                'Okpokwu',
                'Otukpo',
                'Tarka',
                'Ushongo',
                'Vandeikya'
            ],
            'Borno' => [
                'Bayo',
                'Biu',
                'Chibok',
                'Damboa',
                'Dikwa',
                'Guzamala',
                'Abadam',
                'Askira/Uba',
                'Bama',
                'Gwoza',
                'Kaga',
                'Maiduguri',
                'Marte',
                'Mobbar',
                'Monguno',
                'Konduga',
                'Kukawa',
                'Hawul',
                'Jere',
                'Kwaya Kusar',
                'Mafa',
                'Magumeri',
                'Ngala',
                'Nganzai',
                'Shani'
            ],
            'Cross River' => [
                'Calabar Municipal',
                'Calabar South',
                'Etung',
                'Ikom',
                'Obanliku',
                'Abi',
                'Akamkpa',
                'Biase',
                'Boki',
                'Obubra',
                'Obudu',
                'Odukpani',
                'Akpabuyo',
                'Bakassi',
                'Bekwarra',
                'Ogoja',
                'Yakuur',
                'Yala'
            ],
            'Delta' => [
                'Ethiope West',
                'Ethiope East',
                'Ika South',
                'Ika North East',
                'Isoko South',
                'Isoko North',
                'Aniocha South',
                'Aniocha North',
                'Bomadi',
                'Burutu',
                'Ukwuani',
                'Udu',
                'Warri Central',
                'Warri North',
                'Warri South',
                'Okpe',
                'Oshimili North',
                'Oshimili South',
                'Patani',
                'Sapele',
                'Ndokwa East',
                'Ndokwa West',
                'Ughelli South',
                'Ughelli North'
            ],
            'Ebonyi' => [
                'Izzi',
                'Abakaliki',
                'Ezza North',
                'Ivo',
                'Afikpo South',
                'Ohaozara',
                'Afikpo North',
                'Ebonyi',
                'Ohaukwu',
                'Onicha',
                'Ezza South',
                'Ikwo',
                'Ishielu'
            ],
            'Edo' => [
                'Igueben',
                'Ikpoba-Okha',
                'Oredo',
                'Akoko-Edo',
                'Egor',
                'Esan Central',
                'Esan North-East',
                'Esan South-East',
                'Esan West',
                'Orhionmwon',
                'Ovia North-East',
                'Ovia South-West',
                'Etsako Central',
                'Etsako East',
                'Etsako West',
                'Owan East',
                'Owan West',
                'Uhunmwonde'
            ],
            'Ekiti' => [
                'Efon',
                'Emure',
                'Ido-Osi',
                'Ijero',
                'Ado-Ekiti',
                'Ikere',
                'Oye',
                'Aiyekire',
                'Ikole',
                'Ilejemeje',
                'Irepodun/Ifelodun',
                'Ekiti East',
                'Ekiti South-West',
                'Ekiti West',
                'Ise/Orun',
                'Moba'
            ],
            'Enugu' => [
                'Ezza South',
                'Ikwo',
                'Igbo Eze South',
                'Aninri',
                'Awgu',
                'Isi Uzo',
                'Nkanu East',
                'Nkanu West',
                'Nsukka',
                'Ishielu',
                'Enugu East',
                'Enugu North',
                'Enugu South',
                'Oji River',
                'Udenu',
                'Udi',
                'Ezeagu',
                'Igbo Etiti',
                'Igbo Eze North',
                'Uzo-Uwani'
            ],
            'Gombe' => [
                'Akko',
                'Balanga',
                'Billiri',
                'Dukku',
                'Dukwaye',
                'Gombe',
                'Kaltungo',
                'Kwami',
                'Nafada/Bajoga',
                'Shomgom',
                'Yamaltu/Deba'
            ],
            'Imo' => [
                'Ezinihitte Mbaise',
                'Ideato North',
                'Ideato South',
                'Ihitte/Uboma',
                'Aboh Mbaise',
                'Ahiazu Mbaise',
                'Ehime Mbano',
                'Njaba',
                'Nkwerre',
                'Nwangele',
                'Obowo',
                'Oguta',
                'Ikeduru',
                'Isiala Mbano',
                'Isu',
                'Mbaitoli',
                'Ngor Okpala',
                'Ohaji/Egbema',
                'Oru East',
                'Oru West',
                'Owerri Municipal',
                'Okigwe',
                'Onuimo',
                'Orlu',
                'Orsu',
                'Owerri North',
                'Owerri West'
            ],
            'Jigawa' => [
                'Buji',
                'Dutse',
                'Gagarawa',
                'Garki',
                'Gumel',
                'Guri',
                'Gwaram',
                'Gwiwa',
                'Auyo',
                'Babura',
                'Biriniwa',
                'Birnin Kudu',
                'Hadejia',
                'Jahun',
                'Kafin Hausa',
                'Kaugama',
                'Kazaure',
                'Kiri Kasama',
                'Kiyawa',
                'Maigatari',
                'Malam Madori',
                'Miga',
                'Ringim',
                'Roni',
                'Sule Tankarkar',
                'Taura',
                'Yankwashi'
            ],
            'Kaduna' => [
                'Kaduna North',
                'Kaduna South',
                'Birnin Gwari',
                'Chikun',
                'Giwa',
                'Igabi',
                'Kagarko',
                'Kajuru',
                'Kaura',
                'Kauru',
                'Kubau',
                'Kudan',
                'Ikara',
                'Jaba',
                'Jema’a',
                'Kachia',
                'Lere',
                'Makarfi',
                'Soba',
                'Zangon Kataf',
                'Sabon Gari',
                'Sanga',
                'Zaria'
            ],
            'Kano' => [
                'Ajingi',
                'Albasu',
                'Minjibir',
                'Nassarawa',
                'Rano',
                'Bagwai',
                'Bebeji',
                'Bichi',
                'Dawakin Tofa',
                'Doguwa',
                'Fagge',
                'Gabasawa',
                'Garko',
                'Garun Mallam',
                'Gaya',
                'Gezawa',
                'Gwale',
                'Gwarzo',
                'Bunkure',
                'Dala',
                'Dambatta',
                'Dawakin Kudu',
                'Kabo',
                'Kano Municipal',
                'Karaye',
                'Kibiya',
                'Kiru',
                'Kumbotso',
                'Kunchi',
                'Kura',
                'Madobi',
                'Makoda',
                'Rimin Gado',
                'Rogo',
                'Shanono',
                'Sumaila',
                'Takai',
                'Tarauni',
                'Tofa',
                'Tsanyawa',
                'Tudun Wada',
                'Ungogo',
                'Warawa',
                'Wudil'
            ],
            'Katsina' => [
                'Bindawa',
                'Charanchi',
                'Dan Musa',
                'Dandume',
                'Danja',
                'Bakori',
                'Batagarawa',
                'Batsari',
                'Baure',
                'Daura',
                'Dutsi',
                'Jibia',
                'Kafur',
                'Kaita',
                'Kankara',
                'Dutsin-Ma',
                'Faskari',
                'Funtua',
                'Ingawa',
                'Kankia',
                'Katsina',
                'Kurfi',
                'Kusada',
                'Mai’Adua',
                'Malumfashi',
                'Mani',
                'Mashi',
                'Matazu',
                'Musawa',
                'Rimi',
                'Sabuwa',
                'Safana',
                'Sandamu',
                'Zango'
            ],
            'Kebbi' => [
                'Dandi',
                'Fakai',
                'Gwandu',
                'Jega',
                'Arewa Dandi',
                'Argungu',
                'Augie',
                'Kalgo',
                'Sakaba',
                'Shanga',
                'Suru',
                'Koko/Besse',
                'Maiyama',
                'Ngaski',
                'Danko/Wasagu',
                'Yauri',
                'Zuru',
                'Aleiro',
                'Bagudo',
                'Birnin Kebbi',
                'Bunza'
            ],
            'Kogi' => [
                'Dekina',
                'Ibaji',
                'Idah',
                'Igalamela-Odolu',
                'Adavi',
                'Ajaokuta',
                'Ankpa',
                'Bassa',
                'Ijumu',
                'Ofu',
                'Ogori/Magongo',
                'Okehi',
                'Okene',
                'Olamaboro',
                'Kabba/Bunu',
                'Kogi',
                'Lokoja',
                'Mopa-Muro',
                'Omala',
                'Yagba East',
                'Yagba West'
            ],
            'Lagos' => [
                'Apapa',
                'Mushin',
                'Ojo',
                'Oshodi-Isolo',
                'Shomolu',
                'Surulere',
                'Badagry',
                'Epe',
                'Eti-Osa',
                'Ibeju-Lekki',
                'Ifako/Ijaye',
                'Ikeja',
                'Agege',
                'Ajeromi-Ifelodun',
                'Alimosho',
                'Amuwo-Odofin',
                'Ikorodu',
                'Kosofe',
                'Lagos Island',
                'Lagos Mainland'
            ],
            'Nasarawa' => [
                'Karu',
                'Nasarawa',
                'Nasarawa/Eggon',
                'Obi',
                'Toto',
                'Wamba',
                'Keana',
                'Keffi',
                'Kokona',
                'Akwanga',
                'Awe',
                'Doma',
                'Lafia'
            ],
            'Niger' => [
                'Gurara',
                'Katcha',
                'Bosso',
                'Chanchaga',
                'Edati',
                'Gbako',
                'Bida',
                'Borgu',
                'Lapai',
                'Lavun',
                'Kontagora',
                'Agaie',
                'Agwara',
                'Rafi',
                'Magama',
                'Mariga',
                'Mashegu',
                'Mokwa',
                'Rijau',
                'Shiroro',
                'Suleja',
                'Munya',
                'Paikoro',
                'Tafa',
                'Wushishi'
            ],
            'Ogun' => [
                'Ifo',
                'Ijebu East',
                'Ijebu North',
                'Ijebu North East',
                'Abeokuta North',
                'Abeokuta South',
                'Ado-Odo/Ota',
                'Imeko Afon',
                'Ipokia',
                'Obafemi Owode',
                'Odogbolu',
                'Sagamu',
                'Yewa North',
                'Yewa South',
                'Ewekoro',
                'Ijebu Ode',
                'Ikenne',
                'Odeda',
                'Ogun Waterside',
                'Remo North'
            ],
            'Ondo' => [
                'Akoko North',
                'Akoko North East',
                'Akoko South East',
                'Ondo',
                'Ondo East',
                'Ose',
                'Owo',
                'Akoko South',
                'Akure North',
                'Akure',
                'Idanre',
                'Irele',
                'Odigbo',
                'Okitipupa',
                'Ifedore',
                'Ese Odo',
                'Ilaje',
                'Ile Oluji/Okeigbo'
            ],
            'Kwara' => [
                'Asa',
                'Baruten',
                'Edu',
                'Ekiti',
                'Ifelodun',
                'Ilorin East',
                'Ilorin South',
                'Ilorin West',
                'Irepodun',
                'Isin',
                'Kaiama',
                'Moro',
                'Offa',
                'Oke Ero',
                'Oyun',
                'Pategi'
            ],
            'Osun' => [
                'Bolawaduro',
                'Boripe',
                'Ede',
                'Ede North',
                'Atakumosa West',
                'Atakumosa East',
                'Ayedaade',
                'Ayedire',
                'Ife South',
                'Ife East',
                'Ifedayo',
                'Ifelodun',
                'Ilesha West',
                'Egbedore',
                'Ejigbo',
                'Ife North',
                'Ife Central',
                'Ila Orangun',
                'Ilesha East',
                'Irepodun',
                'Ola Oluwa',
                'Olorunda',
                'Oriade',
                'Orolu',
                'Osogbo',
                'Irewole',
                'Isokan',
                'Iwo',
                'Obokun',
                'Odo Otin'
            ],
            'Oyo' => [
                'Akinyele',
                'Afijio',
                'Ido',
                'Irepo',
                'Iseyin',
                'Egbeda',
                'Ibadan North',
                'Ibadan North-East',
                'Ibadan North-West',
                'Ibadan South-West',
                'Ibadan South-East',
                'Ibarapa Central',
                'Ibarapa East',
                'Kajola',
                'Lagelu',
                'Atisbo',
                'Saki West',
                'Saki East',
                'Ogbomosho North',
                'Ogbomosho South',
                'Oyo West',
                'Atiba',
                'Itesiwaju',
                'Iwajowa',
                'Surulere',
                'Orelope',
                'Ori Ire',
                'Ibarapa North',
                'Olorunsogo',
                'Oluyole',
                'Ogo Oluwa',
                'Oyo East',
                'Ona Ara'
            ],
            'Plateau' => [
                'Bokkos',
                'Jos East',
                'Kanam',
                'Barkin Ladi',
                'Bassa',
                'Kanke',
                'Langtang North',
                'Jos North',
                'Jos South',
                'Langtang South',
                'Riyom',
                'Shendam',
                'Wase',
                'Mangu',
                'Mikang',
                'Pankshin',
                'Qua’an Pan'
            ],
            'Rivers' => [
                'Abua-Odual',
                'Ahoada East',
                'Asari-Toru',
                'Bonny',
                'Etche',
                'Gokana',
                'Ikwerre',
                'Degema',
                'Ahoada West',
                'Akuku-Toru',
                'Andoni',
                'Eleme',
                'Emohua',
                'Oyigbo',
                'Khana',
                'Omumma',
                'Opobo-Nkoro',
                'Port Harcourt',
                'Tai',
                'Obio-Akpor',
                'Ogba-Egbema-Ndoni',
                'Ogu-Bolo',
                'Okrika'
            ],
            'Sokoto' => [
                'Gada',
                'Isa',
                'Kebbe',
                'Kware',
                'Rabah',
                'Goronyo',
                'Gudu',
                'Gwadabawa',
                'Illela',
                'Sabon Birni',
                'Binji',
                'Bodinga',
                'Dange Shuni',
                'Shagari',
                'Tureta',
                'Wamako',
                'Wurno',
                'Yabo',
                'Silame',
                'Sokoto North',
                'Sokoto South',
                'Tambuwal',
                'Tangaza'
            ],
            'Taraba' => [
                'Ardo Kola',
                'Bali',
                'Gassol',
                'Ibi',
                'Jalingo',
                'Donga',
                'Gashaka',
                'Karim Lamido',
                'Kurmi',
                'Wukari',
                'Yorro',
                'Zing',
                'Lau',
                'Sardauna',
                'Takum',
                'Ussa'
            ],
            'Yobe' => [
                'Fune',
                'Jakusko',
                'Karasuwa',
                'Machina',
                'Bade',
                'Bursari',
                'Damaturu',
                'Geidam',
                'Gujba',
                'Potiskum',
                'Tarmuwa',
                'Gulani',
                'Fika',
                'Nangere',
                'Nguru',
                'Yunusari',
                'Yusufari'
            ],
            'Zamfara' => [
                'Bungudu',
                'Tsafe',
                'Shinkafi',
                'Talata Mafara',
                'Zurmi',
                'Anka',
                'Bakura',
                'Birnin Magaji/Kiyaw',
                'Bukkuyum',
                'Gummi',
                'Gusau',
                'Kaura Namoda',
                'Maradun',
                'Maru'
            ],
            'FCT' => [
                'Gwagwalada',
                'Kuje',
                'Bwari',
                'Abaji',
                'Abuja Municipal',
                'Kwali'
            ],
        ];

        foreach ($lgasData as $stateName => $lgaNames) {
            $stateId = DB::table('states')->where('name', $stateName)->value('id');
            if ($stateId) {
                foreach ($lgaNames as $lgaName) {
                    DB::table('lgas')->insert([
                        'state_id' => $stateId,
                        'name' => $lgaName,
                    ]);
                }
            }
        }
    }
}
