<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Faculty;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PaymentSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settingsData = [
            // Fresh Students (Non-Education courses, 100 level, FMSS and FSC)
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'REGULAR',
                'amount' => 300000.00,
                'description' => 'Tuition fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'accommodation',
                'student_type' => 'REGULAR',
                'amount' => 100000.00,
                'description' => 'Accommodation fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'maintenance',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Maintenance fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'medical',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Medical fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'id_card',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'ID card fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'ict',
                'student_type' => 'REGULAR',
                'amount' => 35000.00,
                'description' => 'ICT fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'sport',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Sport fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'src',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'SRC fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'entrepreneurship',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Entrepreneurship fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'departmental',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Departmental fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FMSS',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'faculty',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Faculty fee for 100 level Non-Education students in FMSS',
                'session' => activeSession()->name,
            ],
            // Repeat for FSC
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'REGULAR',
                'amount' => 300000.00,
                'description' => 'Tuition fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'accommodation',
                'student_type' => 'REGULAR',
                'amount' => 100000.00,
                'description' => 'Accommodation fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'maintenance',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Maintenance fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'medical',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Medical fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'id_card',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'ID card fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'ict',
                'student_type' => 'REGULAR',
                'amount' => 35000.00,
                'description' => 'ICT fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'sport',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Sport fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'src',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'SRC fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'entrepreneurship',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Entrepreneurship fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'departmental',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Departmental fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FSC',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'faculty',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Faculty fee for 100 level Non-Education students in FSC',
                'session' => activeSession()->name,
            ],
            // Fresh Students (Education courses, 100 level, FE)
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'REGULAR',
                'amount' => 150000.00,
                'description' => 'Tuition fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'accommodation',
                'student_type' => 'REGULAR',
                'amount' => 100000.00,
                'description' => 'Accommodation fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'maintenance',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Maintenance fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'medical',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Medical fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'id_card',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'ID card fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'ict',
                'student_type' => 'REGULAR',
                'amount' => 35000.00,
                'description' => 'ICT fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'sport',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Sport fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'src',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'SRC fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'entrepreneurship',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Entrepreneurship fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'departmental',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Departmental fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => 'FE',
                'department_code' => null,
                'level' => [100],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'faculty',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Faculty fee for 100 level Education students in FE',
                'session' => activeSession()->name,
            ],
            // Returning Students (200, 300, 400 levels, all faculties)
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'REGULAR',
                'amount' => 300000.00,
                'description' => 'Tuition fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'accommodation',
                'student_type' => 'REGULAR',
                'amount' => 100000.00,
                'description' => 'Accommodation fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'maintenance',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Maintenance fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'medical',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Medical fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'id_card',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'ID card fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'ict',
                'student_type' => 'REGULAR',
                'amount' => 35000.00,
                'description' => 'ICT fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'sport',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Sport fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'src',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'SRC fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'entrepreneurship',
                'student_type' => 'REGULAR',
                'amount' => 10000.00,
                'description' => 'Entrepreneurship fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'departmental',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Departmental fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'faculty',
                'student_type' => 'REGULAR',
                'amount' => 5000.00,
                'description' => 'Faculty fee for 200, 300, 400 level returning students',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'TOPUP',
                'amount' => 150000.00,
                'description' => 'Tuition fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'IDELUTME',
                'amount' => 150000.00,
                'description' => 'Tuition fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'tuition',
                'student_type' => 'IDELDE',
                'amount' => 150000.00,
                'description' => 'Tuition fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'administrative',
                'student_type' => 'TOPUP',
                'amount' => 30000.00,
                'description' => 'Administrative fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'administrative',
                'student_type' => 'IDELUTME',
                'amount' => 30000.00,
                'description' => 'Administrative fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
            [
                'faculty_code' => null,
                'department_code' => null,
                'level' => [100, 200, 300, 400],
                'sex' => null,
                'matric_number' => null,
                'payment_type' => 'administrative',
                'student_type' => 'IDELDE',
                'amount' => 30000.00,
                'description' => 'Administrative fee for non regular students in FMSS',
                'session' => activeSession()->name,
            ],
        ];

        foreach ($settingsData as $data) {
            // Find faculty if code provided
            $facultyId = null;
            if (! empty($data['faculty_code'])) {
                $faculty = Faculty::where('faculty_code', $data['faculty_code'])->first();
                if (! $faculty) {
                    $this->command->warn("Faculty {$data['faculty_code']} not found. Skipping...");

                    continue;
                }
                $facultyId = $faculty->id;
            }

            // Find department if code provided
            $departmentId = null;
            if (! empty($data['department_code'])) {
                $department = Department::where('department_code', $data['department_code'])
                    ->where('faculty_id', $facultyId)
                    ->first();
                if (! $department) {
                    $this->command->warn("Department {$data['department_code']} not found. Skipping...");

                    continue;
                }
                $departmentId = $department->id;
            }

            // Insert payment setting
            DB::table('payment_settings')->insert([
                'id' => Str::uuid(),
                'faculty_id' => $facultyId,
                'department_id' => $departmentId,
                'level' => json_encode($data['level']),
                'sex' => $data['sex'],
                'matric_number' => $data['matric_number'],
                'payment_type' => $data['payment_type'],
                'amount' => $data['amount'],
                'description' => $data['description'],
                'student_type' => $data['student_type'],
                'session' => $data['session'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
