<?php

namespace Database\Seeders;

use App\Models\Campus;
use App\Models\Department;
use App\Models\Student;
use App\Models\User;
use App\Models\UserType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        // 🔹 Get student user type
        $studentType = UserType::where('name', 'student')->first();
        if (! $studentType) {
            $this->command->error(" User type 'student' not found. Please seed user_types first.");

            return;
        }

        // 🔹 Pick a campus
        $campus = Campus::first();
        if (! $campus) {
            $this->command->error(' No campus found. Please seed campuses first.');

            return;
        }

        // 🔹 Define students
        $students = [
            [
                'FIRST NAME' => 'BUSARI',
                'LAST NAME' => 'QUDUS',
                'MIDDLENAME' => 'ADEKUNLE',
                'EMAIL' => 'adigunaditu3@gmail.com',
                'PHONE' => '09015866532',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '19-Mar-83',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ORIOKO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADETOLU',
                'LAST NAME' => 'HANNAH',
                'MIDDLENAME' => 'OLUWATOSIN',
                'EMAIL' => 'adetoluhannaholuwatosin8@gmail.com',
                'PHONE' => '08076378455',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '12-Feb-82',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OGUNTE NLA COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'AJAYI',
                'LAST NAME' => 'RUKAYAT',
                'MIDDLENAME' => 'IYABO',
                'EMAIL' => 'ajayirukayatiyabo@gmail.com',
                'PHONE' => '07058515999',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '1-Dec-88',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOMU COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADISA',
                'LAST NAME' => 'NIMOTALLAHI',
                'MIDDLENAME' => 'DAMOLA',
                'EMAIL' => 'adisanimotallahidamola@gmail.com',
                'PHONE' => '08087211336',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '9-Oct-85',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'SERIKI COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLAWORE',
                'LAST NAME' => 'ELIZABETH',
                'MIDDLENAME' => 'ADEBOLA',
                'EMAIL' => 'bolizzy72@gmail.com',
                'PHONE' => '07018025698',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '6-May-72',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ALABI-AGBE NUD 3 PRY SCHL, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ABDULKAREEM',
                'LAST NAME' => 'KAFAYAT',
                'MIDDLENAME' => 'ADETOPE',
                'EMAIL' => 'kafayatadetope@gmail.com',
                'PHONE' => '08055224586',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '12-May-90',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOGBOJO COMPOUND, OJA OBA IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'SULAIMAN',
                'LAST NAME' => 'RUQAYAT',
                'MIDDLENAME' => 'OMOLARA',
                'EMAIL' => 'rukayatazeez2024@gmail.com',
                'PHONE' => '09116867767',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '1-Oct-90',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OKE AAGO COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ABDULAZEEZ',
                'LAST NAME' => 'KAFILAT',
                'MIDDLENAME' => 'FOYEKE',
                'EMAIL' => 'kafilatfoyeke41@gmail.com',
                'PHONE' => '08052875847',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '19-Apr-77',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'BALODE HOUSE, ALONG ISLAMIC HIGH SCHOOL, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'RABIU',
                'LAST NAME' => 'RUKAYAT',
                'MIDDLENAME' => 'AFOLASHADE',
                'EMAIL' => 'rabiurukayatafolashade27@gmail.com',
                'PHONE' => '09153094557',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '27-Apr-83',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OKE-ODO AMO ALONG BANNI ROAD IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLAWOYIN',
                'LAST NAME' => 'NOAH',
                'MIDDLENAME' => 'TAIWO',
                'EMAIL' => 'ntolawoyin77@gmail.com',
                'PHONE' => '09020088412',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '400',
                'DOB' => '27-Apr-77',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ASIPA AYELABOWO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'KAREEM',
                'LAST NAME' => 'ASISAT',
                'MIDDLENAME' => 'TEMILADE',
                'EMAIL' => 'kareemasisat@gmail.com',
                'PHONE' => '08053140893',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '5-Mar-87',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'SAAGBON COMPOUND IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLAWOYIN',
                'LAST NAME' => 'JACOB',
                'MIDDLENAME' => 'KEHINDE',
                'EMAIL' => 'jkolawoyin77@gmail.com',
                'PHONE' => '08079553980',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '400',
                'DOB' => '27-Apr-77',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ASIPA AYELABOWO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ABUBAKAR',
                'LAST NAME' => 'AKEEM',
                'MIDDLENAME' => 'ADEBAYO',
                'EMAIL' => 'abubakarakeem25@gmail.com',
                'PHONE' => '07059630938',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'AGRIC EDUCATION',
                'FACULTY' => 'VOCATIONAL & TECHNICAL',
                'LEVEL' => '300',
                'DOB' => '24-Apr-85',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'SAAGBON COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLADELE',
                'LAST NAME' => 'JOHN',
                'MIDDLENAME' => 'OLUFEMI',
                'EMAIL' => 'olamidi330@gmail.com',
                'PHONE' => '07050208565',
                'PROGRAMME' => 'IDELUTME',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '200',
                'DOB' => '2-Dec-87',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'NO4 OLADELE VILLA, OKE GENERAL HOSPITAL AREA, IGBETI',
                'MODE OF ENTRY' => 'IDELUTME',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ISHOLA',
                'LAST NAME' => 'REBECCA',
                'MIDDLENAME' => 'BOLUWATIFE',
                'EMAIL' => 'boluwatifeishola667@gmail.com',
                'PHONE' => '07019820028',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '3-Apr-03',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ELERUGBA COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'AMINU',
                'LAST NAME' => 'RAUFU',
                'MIDDLENAME' => '',
                'EMAIL' => 'aminuraufu74@gmail.com',
                'PHONE' => '07051333097',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '22-Nov-79',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLORO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'SULAIMAN',
                'LAST NAME' => 'BASIRU',
                'MIDDLENAME' => 'OLAWALE',
                'EMAIL' => 'sulaimanbasiru646@gmail.com',
                'PHONE' => '08071897277',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '1-Jan-95',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ASIPA AGORO, OKE AGO IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'BADMUS',
                'LAST NAME' => 'MUTIU',
                'MIDDLENAME' => 'ADEPOJU',
                'EMAIL' => 'badmusmutiu007@gmail.com',
                'PHONE' => '08057200660',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '20-Oct-81',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOKO COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ISHOLA',
                'LAST NAME' => 'MAYOKUN',
                'MIDDLENAME' => 'EMMANUEL',
                'EMAIL' => 'isholamayokun77@gmail.com',
                'PHONE' => '08025545219',
                'PROGRAMME' => 'IDELUTME',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '23-Feb-05',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ISOLABA COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDELUTME',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'IBRAHIM',
                'LAST NAME' => 'AFEEZ',
                'MIDDLENAME' => 'ADIO',
                'EMAIL' => 'afeezibrahim61@gmail.com',
                'PHONE' => '08027701641',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '20-Nov-88',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'APALA COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ASAMU',
                'LAST NAME' => 'EUNICE',
                'MIDDLENAME' => 'DOLAPO',
                'EMAIL' => 'asamueunice4@gmail.com',
                'PHONE' => '09044693301',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'BUSINESS STUDIES EDUCATION',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '400',
                'DOB' => '6-Jan-98',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => "ASAMU'S VILLA OLOSUN AREA, IGBETI",
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'AZEEZ',
                'LAST NAME' => 'MUHIDEEN',
                'MIDDLENAME' => 'AKANBI',
                'EMAIL' => 'muhideenazeez7@gmail.com',
                'PHONE' => '08153603523',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '5-Mar-85',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLORO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLABIWONNU',
                'LAST NAME' => 'EUNICE',
                'MIDDLENAME' => 'IFEOLUWA',
                'EMAIL' => 'olanbiwonnueunice@gmail.com',
                'PHONE' => '07011124854',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'MCB',
                'FACULTY' => 'FACULTY OF SCIENCE & COMPUTING',
                'LEVEL' => '300',
                'DOB' => '5-Nov-00',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOGBOJO COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLAJIDE',
                'LAST NAME' => 'OLADEJO',
                'MIDDLENAME' => 'THEOPHILUS',
                'EMAIL' => 'theophilusolajide66@gmail.com',
                'PHONE' => '08112464893',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'MCB',
                'FACULTY' => 'FACULTY OF SCIENCE & COMPUTING',
                'LEVEL' => '400',
                'DOB' => '8-Jul-66',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'SERIKI HOUSE, BEHIND ARIJE HOTE, OKE AYO IGBETI',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLATUNJI',
                'LAST NAME' => 'OLALEKAN',
                'MIDDLENAME' => 'OLUWASEUN',
                'EMAIL' => 'olatunjiolalekanoluwaseun@gmail.com',
                'PHONE' => '09019043498',
                'PROGRAMME' => 'IDELUTME',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'MCB',
                'FACULTY' => 'FACULTY OF SCIENCE & COMPUTING',
                'LEVEL' => '300',
                'DOB' => '27-Apr-05',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOKO COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDELUTME',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'EMMANUEL',
                'LAST NAME' => 'JOHN',
                'MIDDLENAME' => '',
                'EMAIL' => 'sirjohnemmanuel1@gmail.com',
                'PHONE' => '07035495500',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'ECO',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '16-Nov-97',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'BANI KAIAMA LGE, KWARA STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLATUNJI',
                'LAST NAME' => 'AMUSAN',
                'MIDDLENAME' => 'SUNDAY',
                'EMAIL' => 'amusanolatunji7@gmail.com',
                'PHONE' => '08033998236',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SWE',
                'FACULTY' => 'SCIENCE AND COMPUTING',
                'LEVEL' => '400',
                'DOB' => '12-Apr-81',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'AFIJIO',
                'CITY' => 'IBADAN',
                'ADDRESS' => '3 BLOCK D LANE 7 ARUBIEWE ZONE 2 OLODO IBADAN',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'JOLAIYA',
                'LAST NAME' => 'DEBORAH',
                'MIDDLENAME' => 'OLAWUMI',
                'EMAIL' => 'jolaiyadeborah66@gmail.com',
                'PHONE' => '08077337219',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '14-Jan-89',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'KOGI',
                'LGA' => 'YAGBA WEST',
                'CITY' => 'IBADAN',
                'ADDRESS' => 'NO 2, IFESOWAPO STREET OLOSAN ALAKIA, IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLUWADAMILOLA',
                'LAST NAME' => 'TAIWO',
                'MIDDLENAME' => 'ESTHER',
                'EMAIL' => 'oludamitaiwo6@gmail.com',
                'PHONE' => '08068245357',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '4-Apr-83',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'IBADAN NORTH-WEST',
                'CITY' => 'IBADAN',
                'ADDRESS' => 'NW7/448 LIASU LAYOUT, ISABEL ST. BENJAMIN AREA, ELEYELE IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLUSAYO',
                'LAST NAME' => 'OWOMOYELA',
                'MIDDLENAME' => 'ABOSEDE',
                'EMAIL' => 'owomoyelaabosede@gmail.com',
                'PHONE' => '09078144594',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '14-Nov-76',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'EGBEDA',
                'CITY' => 'IBADAN',
                'ADDRESS' => 'NO 3, HARMONY ESTATE, IDI OSAN, OLODO, OFF IWO ROAD, IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLUKOYA',
                'LAST NAME' => 'AMINAT',
                'MIDDLENAME' => 'AFOLASHADE',
                'EMAIL' => 'olukoyaaminat76@gmail.com',
                'PHONE' => '08037641570',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SWE',
                'FACULTY' => 'SCIENCE AND COMPUTING',
                'LEVEL' => '400',
                'DOB' => '4-Oct-76',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OGUN',
                'LGA' => 'IJEBU NORTH',
                'CITY' => 'AGO-IWOYE',
                'ADDRESS' => 'NO 2, BOJOWA STREET, IBIPE, OGUN STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLUWATOBI',
                'LAST NAME' => 'YUSUF',
                'MIDDLENAME' => 'ADEDOYIN',
                'EMAIL' => 'yoluwatobiisreal@gmail.com',
                'PHONE' => '08166257120',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SWE',
                'FACULTY' => 'SCIENCE AND COMPUTING',
                'LEVEL' => '400',
                'DOB' => '4-Oct-95',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'EGBEDA',
                'CITY' => 'IBADAN',
                'ADDRESS' => '2, AGBEDO STREET OLODO AREA, IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'BABATUNDE',
                'LAST NAME' => 'MARY',
                'MIDDLENAME' => 'IBUKUNOLUWA',
                'EMAIL' => 'ibukunoluwamary20@gmail.com',
                'PHONE' => '070377646884',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SWE',
                'FACULTY' => 'SCIENCE AND COMPUTING',
                'LEVEL' => '400',
                'DOB' => '14-Sep-93',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OSUN',
                'LGA' => 'IFE EAST',
                'CITY' => 'ILE-IFE',
                'ADDRESS' => '3, ORI OKE AANUN ESTATE ISOKUN OJOO IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLADIPUPO',
                'LAST NAME' => 'GANIYAT',
                'MIDDLENAME' => 'BUKOLA',
                'EMAIL' => 'adebuky218@gmail.com',
                'PHONE' => '08059415930',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '21-Dec-80',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OYO',
                'LGA' => 'EGBEDA',
                'CITY' => 'IBADAN',
                'ADDRESS' => 'NO 1, ADEGBAYI OLODE OFF OGUNGBADE ROAD, IBADAN, OYO STAYE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'AYOADE',
                'LAST NAME' => 'YUSUFF',
                'MIDDLENAME' => 'ADETUNJI',
                'EMAIL' => 'ayoadeyusuff55@gmail.com',
                'PHONE' => '09039191357',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '12-Dec-91',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'OSUN',
                'LGA' => 'IREWOLE',
                'CITY' => 'IBADAN',
                'ADDRESS' => '54, IFETEDO OLODO AREA, IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADESOLA',
                'LAST NAME' => 'PRECIOUS',
                'MIDDLENAME' => 'OLUFUNMILAYO',
                'EMAIL' => 'funmiadesola2004@gmail.com',
                'PHONE' => '07036382354',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '300',
                'DOB' => '6-Sep-76',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'EKITI',
                'LGA' => 'OYE',
                'CITY' => 'ISAN EKITI',
                'ADDRESS' => '4, KENGBE STREET ISEBO, ALAKIA AREA, IBADAN, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OMOLOJA',
                'LAST NAME' => 'OLUWASEYI',
                'MIDDLENAME' => '',
                'EMAIL' => 'omolojaseyi@gmail.com',
                'PHONE' => '08037139866',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'CSC',
                'FACULTY' => 'SCIENCE AND COMPUTING',
                'LEVEL' => '400',
                'DOB' => '21-Jul-80',
                'NATIONALITY' => 'NIGERIAN',
                'STATE' => 'ONDO',
                'LGA' => 'OWO',
                'CITY' => 'LAGOS',
                'ADDRESS' => 'NO 5, TUNJI ADERINTO STREET, ISOLO, LAGOS STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OLATORERA',
                'LAST NAME' => 'OYERONKE',
                'MIDDLENAME' => 'IYABODE',
                'EMAIL' => 'olatoreraoyeronke@gmail.com',
                'PHONE' => '08138320183',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'ACC',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '400',
                'DOB' => '19-Apr-77',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'BLESSING VILLA KESO, ALONG ILORIN ROAD, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'MOORE',
                'LAST NAME' => 'JULIANAH',
                'MIDDLENAME' => 'BUSOLA',
                'EMAIL' => 'moorejulianahbusola@gmail.com',
                'PHONE' => '08022325278',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '9-Dec-74',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'IYA KUNLE VILLA OPPOSITE GENERAL HOSPITAL IGBETI OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'JIMOH',
                'LAST NAME' => 'SUKURAT',
                'MIDDLENAME' => 'BOLANLE',
                'EMAIL' => 'jimohshukuratomobolanle@gmail.com',
                'PHONE' => '07051134180',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '31-Jul-94',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'FADEYI HOUSE, OKE GENERAL, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'RASAQ',
                'LAST NAME' => 'AMINAT',
                'MIDDLENAME' => '',
                'EMAIL' => 'rasaqaminat19@gmail.com',
                'PHONE' => '08122824148',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '28-Dec-79',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'PAKOYI COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADEAGBO',
                'LAST NAME' => 'CHRISTIANAH',
                'MIDDLENAME' => 'OPEYEMI',
                'EMAIL' => 'adeagbochristianah81@gmail.com',
                'PHONE' => '09071710541',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '31-May-95',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OGUNTE NLA COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'SALAUDEEN',
                'LAST NAME' => 'ABDULWAHAB',
                'MIDDLENAME' => 'ATANDA',
                'EMAIL' => 'salaudeen1147@yahoo.com',
                'PHONE' => '09024448082',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '7-May-89',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'SAKI WEST',
                'CITY' => 'SAKI',
                'ADDRESS' => 'BAALE BAABO SAKI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'LAWAL',
                'LAST NAME' => 'BOLA',
                'MIDDLENAME' => 'GRACE',
                'EMAIL' => 'lawalbolagrace2@gmail.com',
                'PHONE' => '07066838211',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '2-Apr-75',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ASIPA RESIDENCE, OKE-OWODE, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'RABIU',
                'LAST NAME' => 'BALIKIS',
                'MIDDLENAME' => '',
                'EMAIL' => 'balkisrabiu7@gmail.com',
                'PHONE' => '09074030132',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'MCB',
                'FACULTY' => 'FACULTY OF SCIENCE & COMPUTING',
                'LEVEL' => '200',
                'DOB' => '30-Jan-00',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OKUTA-PETE IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'YUNUS',
                'LAST NAME' => 'MARYAM',
                'MIDDLENAME' => 'ABIKE',
                'EMAIL' => 'adeyemiabike360@gmail.com',
                'PHONE' => '09122356229',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'MCB',
                'FACULTY' => 'FACULTY OF SCIENCE & COMPUTING',
                'LEVEL' => '200',
                'DOB' => '24-Apr-01',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLOGBOJO COMPOUND, IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADETOLA',
                'LAST NAME' => 'ATIKAT',
                'MIDDLENAME' => '',
                'EMAIL' => 'atikatadetola@gmail.com',
                'PHONE' => '08051099722',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '12-Feb-72',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'SERIKI COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'AKINBORO',
                'LAST NAME' => 'RASHEEDAT',
                'MIDDLENAME' => 'TEMITOPE',
                'EMAIL' => 'akinbororasheedat@gmail.com',
                'PHONE' => '08143639322',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '10-Jun-81',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OLORO COMPOUND IGBETI',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'BADMOS',
                'LAST NAME' => 'FASILAT',
                'MIDDLENAME' => 'OLAJUMOKE',
                'EMAIL' => 'fataifasilat2020@gmail.com',
                'PHONE' => '09072002184',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '24-Jul-93',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'JARAMOSE COMPOUND, AGBENI AREA, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OGUNSOLA',
                'LAST NAME' => 'MATHEW',
                'MIDDLENAME' => 'GBENRO',
                'EMAIL' => 'mathewgbenroogunsola@gmail.com',
                'PHONE' => '08052947661',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'SSE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '12-Sep-79',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OKE OWODE, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADEBAYO',
                'LAST NAME' => 'REBECCA',
                'MIDDLENAME' => 'OLUWASEUN',
                'EMAIL' => 'adebayorebacca@gmail.com',
                'PHONE' => '08072341849',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'ECE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '8-Jul-81',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'FEKETE COMPOUND, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'OYEKU',
                'LAST NAME' => 'LYDIA',
                'MIDDLENAME' => 'ARIBIKE',
                'EMAIL' => 'lydiaaribike@gmail.com',
                'PHONE' => '08166115880',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'ECE',
                'FACULTY' => 'EDUCATION',
                'LEVEL' => '200',
                'DOB' => '14-Jul-81',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ADENIYI COMPOUND, OKE AGO, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'ADELOWO',
                'LAST NAME' => 'REUBEN',
                'MIDDLENAME' => 'OYINLA',
                'EMAIL' => 'rubenadelowo7@gmail.com',
                'PHONE' => '08081869631',
                'PROGRAMME' => 'IDEL',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'MALE',
                'DEPARTMENT' => 'POL',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '200',
                'DOB' => '9-Sep-99',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'OKE IBUKUN AREA, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDEL',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'RAHEEM',
                'LAST NAME' => 'MISTURA',
                'MIDDLENAME' => 'ADEDOYIN',
                'EMAIL' => 'misturaraheem09@gmail.com',
                'PHONE' => '09011950782',
                'PROGRAMME' => 'IDELUTME',
                'STREAM' => '2',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '200',
                'DOB' => '9-Aug-06',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => 'OYO',
                'LGA' => 'OLORUNSOGO',
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ABOKE COMPOUND, OLOSU AREA, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'IDELUTME',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Igbeti Campus',
            ],
            [
                'FIRST NAME' => 'BILIKIS',
                'LAST NAME' => 'SAAD',
                'MIDDLENAME' => 'IYABO',
                'EMAIL' => 'non@gmail.com',
                'PHONE' => '090',
                'PROGRAMME' => 'TOPUP',
                'STREAM' => '1',
                'SIGNATURE' => '',
                'GENDER' => 'FEMALE',
                'DEPARTMENT' => 'BUS',
                'FACULTY' => 'HUMANITIES, MANAGEMENTS & SOCIAL SCIENCE',
                'LEVEL' => '300',
                'DOB' => '9-Aug-06',
                'NATIONALITY' => 'NIGERIA',
                'STATE' => null,
                'LGA' => null,
                'CITY' => 'IGBETI',
                'ADDRESS' => 'ABOKE COMPOUND, OLOSU AREA, IGBETI, OYO STATE',
                'MODE OF ENTRY' => 'TOPUP',
                'ADMISSIONS' => '2024/2025',
                'CENTER' => 'Ilorin Campus',
            ],
        ];

        foreach ($students as $studentData) {
            // 🔹 Find department
            $department = Department::where('department_code', $studentData['DEPARTMENT'])->first();

            if (! $department) {
                $this->command->warn(" Department {$studentData['DEPARTMENT']} not found. Skipping...");

                continue;
            }

            $admissionYear = explode('/', $studentData['ADMISSIONS'])[0];

            // 🔹 Generate matric number
            $matricNo = Student::generateMatricNo($department->department_code, $admissionYear, $studentData['PROGRAMME']);

            if ($studentData['CENTER']) {
                // 🔹 Find campus
                $campus = Campus::where('name', $studentData['CENTER'])->first();

                if (! $campus) {
                    $this->command->warn(" Campus {$studentData['CENTER']} not found. Skipping...");

                    continue;
                }
            } else {
                $campus = Campus::first();
            }

            // 🔹 Create user
            $user = User::create([
                'id' => Str::uuid(),
                'first_name' => $studentData['FIRST NAME'],
                'last_name' => $studentData['LAST NAME'],
                'middle_name' => $studentData['MIDDLENAME'],
                'email' => $studentData['EMAIL'],
                'phone' => $studentData['PHONE'],
                'username' => $matricNo,
                'registration_no' => null,
                'password' => Hash::make($studentData['LAST NAME']),
                'user_type_id' => $studentType->id,

            ]);

            // 🔹 Create student record
            Student::create([
                'id' => Str::uuid(),
                'user_id' => $user->id,
                'campus_id' => $campus->id,
                'department_id' => $department->id,
                'matric_no' => $matricNo,
                'programme' => $studentData['PROGRAMME'],
                'stream' => $studentData['STREAM'],
                'entry_mode' => $studentData['MODE OF ENTRY'],
                'level' => $studentData['LEVEL'],
                'admission_session' => $studentData['ADMISSIONS'],
                'admission_date' => now(),
                'status' => 1,
                'sex' => $studentData['GENDER'],
            ]);
        }

        $this->command->info('✅ '.count($students).' students seeded successfully.');
    }
}
