<option value="Access Bank">Access Bank</option>
<option value="Access Bank (Diamond)">Access Bank (Diamond)</option>
<option value="ALAT by Wema">ALAT by Wema</option>
<option value="Citibank Nigeria">Citibank Nigeria</option>
<option value="Ecobank Nigeria">Ecobank Nigeria</option>
<option value="Fidelity Bank">Fidelity Bank</option>
<option value="First Bank of Nigeria">First Bank of Nigeria</option>
<option value="First City Monument Bank (FCMB)">First City Monument Bank (FCMB)</option>
<option value="Globus Bank">Globus Bank</option>
<option value="Guaranty Trust Bank (GTBank)">Guaranty Trust Bank (GTBank)</option>
<option value="Heritage Bank">Heritage Bank</option>
<option value="Jaiz Bank">Jaiz Bank</option>
<option value="Keystone Bank">Keystone Bank</option>
<option value="Kuda Microfinance Bank">Kuda Microfinance Bank</option>
<option value="Lotus Bank">Lotus Bank</option>
<option value="Moniepoint Microfinance Bank">Moniepoint Microfinance Bank</option>
<option value="Optimus Bank">Optimus Bank</option>
<option value="PalmPay">PalmPay</option>
<option value="Parallex Bank">Parallex Bank</option>
<option value="Polaris Bank">Polaris Bank</option>
<option value="PremiumTrust Bank">PremiumTrust Bank</option>
<option value="Providus Bank">Providus Bank</option>
<option value="Rand Merchant Bank">Rand Merchant Bank</option>
<option value="Rubies Bank">Rubies Bank</option>
<option value="Sparkle Bank">Sparkle Bank</option>
<option value="Stanbic IBTC Bank">Stanbic IBTC Bank</option>
<option value="Standard Chartered Bank">Standard Chartered Bank</option>
<option value="Sterling Bank">Sterling Bank</option>
<option value="SunTrust Bank">SunTrust Bank</option>
<option value="TAJ Bank">TAJ Bank</option>
<option value="Titan Trust Bank">Titan Trust Bank</option>
<option value="Union Bank of Nigeria">Union Bank of Nigeria</option>
<option value="United Bank for Africa (UBA)">United Bank for Africa (UBA)</option>
<option value="Unity Bank">Unity Bank</option>
<option value="VFD Microfinance Bank">VFD Microfinance Bank</option>
<option value="Wema Bank">Wema Bank</option>
<option value="Zenith Bank">Zenith Bank</option>
